---
abstract: 'Rewrite your DBIC objects via inheritance'
author:
  - 'Curtis "Ovid" Poe, C<< <ovid at cpan.org> >>'
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
build_requires:
  DBIx::Class::EasyFixture: '0.02'
  ExtUtils::MakeMaker: 6.59
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Objects
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Load: 0
  DBIx::Class: 0
  Moose: 0
  MooseX::NonMoose: 0
  MooseX::Role::Parameterized: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class-Objects
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
